Add: Support for capturing outgoing requests
Moesif/moesif-aws-lambda-nodejs pull request #4
Opened 2020-02-24 22:48 UTC by keyur9

Add: Support for capturing outgoing requests
Refactor: Update README.md
Bump version to 1.2.6

2020-02-24 23:02 UTC, dgilling requested changes
We can't batch on AWS Lambda since the process will die. Best just to do async. Does it work? Maybe if implemented that way, we can get away with it with short flush windows?

2020-02-24 23:04 UTC, xinghengwang commented
derric asked to take a look. but looks like mostly a copy of the stuff from Moesif-express. I don't know if this works for AWS.  This is tested, right?

2020-02-24 23:05 UTC, keyur9 commented
Yes, it is tested for AWS and it works fine.

2020-02-24 23:06 UTC, xinghengwang approved these changes

2020-02-26 00:56 UTC, dgilling approved these changes

2020-02-26 00:56 UTC, merged